"""Scan projects/ and regenerate assets/js/media_manifest.js.

THIS IS THE CMS. There is no database and no admin server: the folder tree is
the content model, and this script is the publish step.

    1. drop a file into  projects/<id>/<slot>/
    2. run  python _tools/build_media_manifest.py
    3. reload the site

Slots, and what each one does on the page:

    screenshots/hero.jpg     the grid tile and the image at the top of the
                             tool page. Without it the tile falls back to
                             generated placeholder art. (Image A.)
    screenshots/workflow.jpg the technical workflow diagram, shown beside the
                             "how it works" copy rather than in the gallery.
                             (Image B. 'technical' also accepted.)
    screenshots/01.jpg ...   the gallery strip, shown in filename order.
                             Any name works; numbering just controls order.
    videos/*.mp4             inline players, in filename order.
    html/*.html              "Open live preview" buttons.
    docs/*.pdf|*.xlsx|...    download buttons, labelled from the filename.

Anything the site does not have simply does not render — no broken images and
no empty headings. Nothing here is hand-maintained, so the manifest can never
drift from what is actually on disk.
"""
import io, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECTS = os.path.join(ROOT, 'projects')
OUT = os.path.join(ROOT, 'assets', 'js', 'media_manifest.js')

IMG = ('.jpg', '.jpeg', '.png', '.webp', '.gif')
VID = ('.mp4', '.webm', '.mov')
DOC = ('.pdf', '.xlsx', '.xls', '.docx', '.doc', '.pptx', '.csv', '.md', '.zip')

DOC_LABEL = {'.pdf': 'PDF', '.xlsx': 'Workbook', '.xls': 'Workbook',
             '.docx': 'Document', '.doc': 'Document', '.pptx': 'Slides',
             '.csv': 'Data', '.md': 'Notes', '.zip': 'Bundle'}


def listdir(path, exts):
    """Files of the given types, sorted by name, hidden files skipped."""
    if not os.path.isdir(path):
        return []
    return sorted(f for f in os.listdir(path)
                  if not f.startswith('.') and f.lower().endswith(exts))


def title_from(filename):
    stem = os.path.splitext(filename)[0]
    return stem.replace('_', ' ').replace('-', ' ').strip().title()


manifest, stats = {}, {'hero': 0, 'workflow': 0, 'gallery': 0, 'videos': 0, 'html': 0, 'docs': 0}
if not os.path.isdir(PROJECTS):
    raise SystemExit('no projects/ directory at %s' % PROJECTS)

for pid in sorted(os.listdir(PROJECTS)):
    pdir = os.path.join(PROJECTS, pid)
    if not os.path.isdir(pdir):
        continue
    rel = lambda *p: '/'.join(('projects', pid) + p)
    entry = {}

    shots = listdir(os.path.join(pdir, 'screenshots'), IMG)
    hero = next((f for f in shots if os.path.splitext(f)[0].lower() == 'hero'), None)
    if hero:
        entry['hero'] = rel('screenshots', hero)
        stats['hero'] += 1
    # The image procedure calls for two drawings per tool: Image A is the hero,
    # Image B is the technical workflow. Image B has its own slot because it is
    # used in the "how it works" section, not in the gallery strip -- left in
    # the gallery it would read as one screenshot among many.
    workflow = next((f for f in shots
                     if os.path.splitext(f)[0].lower() in ('workflow', 'technical')), None)
    if workflow:
        entry['workflow'] = rel('screenshots', workflow)
        stats['workflow'] = stats.get('workflow', 0) + 1
    gallery = [rel('screenshots', f) for f in shots if f not in (hero, workflow)]
    if gallery:
        entry['gallery'] = gallery
        stats['gallery'] += len(gallery)

    videos = listdir(os.path.join(pdir, 'videos'), VID)
    if videos:
        entry['videos'] = [{'type': 'file', 'src': rel('videos', f),
                            'title': title_from(f)} for f in videos]
        stats['videos'] += len(videos)

    html = listdir(os.path.join(pdir, 'html'), ('.html', '.htm'))
    if html:
        entry['html'] = [rel('html', f) for f in html]
        stats['html'] += len(html)

    docs = listdir(os.path.join(pdir, 'docs'), DOC)
    if docs:
        entry['docs'] = [{'src': rel('docs', f),
                          'title': '%s (%s)' % (title_from(f),
                                                DOC_LABEL.get(os.path.splitext(f)[1].lower(), 'File'))}
                         for f in docs]
        stats['docs'] += len(docs)

    if entry:
        manifest[pid] = entry

body = json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=True)
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(
    '/* GENERATED by _tools/build_media_manifest.py - do not edit by hand.\n'
    ' * Drop files into projects/<id>/{screenshots,videos,html,docs}/ and re-run it.\n'
    ' * %d of %d projects carry media. */\n'
    'window.MEDIA_MANIFEST = %s;\n'
    % (len(manifest), len([d for d in os.listdir(PROJECTS)
                           if os.path.isdir(os.path.join(PROJECTS, d))]), body))

print('projects with media: %d' % len(manifest))
for k, v in stats.items():
    print('  %-8s %d' % (k, v))
print('wrote %s (%.1f KB)' % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT) / 1024.0))
