"""Generate assets/js/projects_data.js from content/<id>.json.

Run this after anything edits the records - the admin does it automatically on
save, and you can run it by hand after editing a JSON file in an editor.

    python _tools/build_content.py

Validation runs first and is fatal. A record that is missing a required field,
or points at an unknown kind/domain/status, stops the build instead of shipping
a broken card to the site. That is deliberate: with 52 records and rising, a
silent bad entry is much more expensive than a failed generate.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, 'content')
OUT = os.path.join(ROOT, 'assets', 'js', 'projects_data.js')

REQUIRED = ('id', 'code', 'name', 'status', 'kind', 'domain', 'tagline')
KINDS = {'plugin', 'dashboard', 'pipeline', 'connector', 'platform', 'agent', 'evaluation', 'deck'}
DOMAINS = {'design', 'docs', 'qa', 'controls', 'knowledge', 'studio', 'ai'}
STATUSES = {'production', 'in-progress', 'experimental', 'research'}

ORDER = ['id', 'code', 'name', 'status', 'kind', 'domain', 'workflowStage',
         'logo', 'tagline', 'description', 'tech', 'efficiency', 'page', 'related']


def load():
    if not os.path.isdir(CONTENT):
        sys.exit('no content/ directory at %s' % CONTENT)
    out = []
    for fn in sorted(os.listdir(CONTENT)):
        if not fn.endswith('.json') or fn.startswith('.'):
            continue
        path = os.path.join(CONTENT, fn)
        try:
            with io.open(path, encoding='utf-8') as f:
                out.append((fn, json.load(f)))
        except ValueError as e:
            sys.exit('%s is not valid JSON: %s' % (fn, e))
    return out


def validate(records):
    errs, seen_id, seen_code = [], {}, {}
    for fn, r in records:
        who = r.get('id') or fn
        for k in REQUIRED:
            if not r.get(k):
                errs.append('%s: missing required field "%s"' % (who, k))
        if r.get('id') and fn != r['id'] + '.json':
            errs.append('%s: filename does not match id "%s"' % (fn, r['id']))
        if r.get('kind') and r['kind'] not in KINDS:
            errs.append('%s: unknown kind "%s"' % (who, r['kind']))
        if r.get('domain') and r['domain'] not in DOMAINS:
            errs.append('%s: unknown domain "%s"' % (who, r['domain']))
        if r.get('status') and r['status'] not in STATUSES:
            errs.append('%s: unknown status "%s"' % (who, r['status']))
        if r.get('id') in seen_id:
            errs.append('%s: duplicate id, also in %s' % (who, seen_id[r['id']]))
        seen_id[r.get('id')] = fn
        if r.get('code') in seen_code:
            errs.append('%s: duplicate code %s, also in %s' % (who, r.get('code'), seen_code[r['code']]))
        seen_code[r.get('code')] = fn
        if 'media' in r:
            errs.append('%s: media does not belong in a record - the folder tree owns it' % who)

    ids = set(seen_id)
    for fn, r in records:
        for rel in r.get('related') or []:
            if rel not in ids:
                errs.append('%s: related points at "%s", which does not exist' % (r.get('id'), rel))
    return errs


def ordered(r):
    out = {}
    for k in ORDER:
        if r.get(k) not in (None, '', [], {}):
            out[k] = r[k]
    for k in r:                       # anything new, kept rather than silently dropped
        if k not in out and r[k] not in (None, '', [], {}):
            out[k] = r[k]
    return out


records = load()
errs = validate(records)
if errs:
    print('VALIDATION FAILED - projects_data.js not written\n')
    for e in errs:
        print('  ' + e)
    sys.exit(1)

data = [ordered(r) for _, r in records]
data.sort(key=lambda r: r.get('code', ''))

body = json.dumps(data, indent=2, ensure_ascii=True)
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(
    '/* GENERATED by _tools/build_content.py - do not edit by hand.\n'
    ' * Source of truth: content/<id>.json (%d records).\n'
    ' * Media is NOT here; see media_manifest.js. */\n'
    'window.CONTENT_PROJECTS = %s;\n' % (len(data), body))

kinds = {}
for r in data:
    kinds[r['kind']] = kinds.get(r['kind'], 0) + 1
print('validated %d records, no errors' % len(data))
print('kinds: %s' % ', '.join('%s %d' % kv for kv in sorted(kinds.items())))
print('wrote %s (%.1f KB)' % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT) / 1024.0))
