"""Scan assets/previews/ and write assets/js/preview_manifest.js.

Runtime probing used to decide whether a card has a preview by pointing a
lazy <img> at assets/previews/<slug>.jpg and waiting for load/error to fire --
below the fold the browser never issues that request, so the check never
resolves and the card falls back to its icon tile even when a real preview
sits on disk. This script replaces the guess with a fact, checked once at
build time: window.PREVIEW_MANIFEST lists every slug that has BOTH
assets/previews/<slug>.jpg and <slug>.mp4.

Run it whenever a preview pair is added or removed:

    python _tools/build_preview_manifest.py
"""
import io, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREVIEWS = os.path.join(ROOT, 'assets', 'previews')
OUT = os.path.join(ROOT, 'assets', 'js', 'preview_manifest.js')

slugs = []
if os.path.isdir(PREVIEWS):
    files = set(f for f in os.listdir(PREVIEWS) if not f.startswith('.'))
    stems = sorted(set(os.path.splitext(f)[0] for f in files))
    for stem in stems:
        if (stem + '.jpg') in files and (stem + '.mp4') in files:
            slugs.append(stem)

body = json.dumps(slugs, indent=2, ensure_ascii=True)
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(
    '/* GENERATED by _tools/build_preview_manifest.py - do not edit by hand.\n'
    ' * Every slug here has BOTH assets/previews/<slug>.jpg and <slug>.mp4.\n'
    ' * %d previews found. Re-run after adding or removing a preview pair. */\n'
    'window.PREVIEW_MANIFEST = %s;\n' % (len(slugs), body))

print('preview manifest: %d slugs' % len(slugs))
for s in slugs:
    print('  ' + s)
print('wrote %s' % os.path.relpath(OUT, ROOT))
